version: "3"

services:
  phoneinfoga:
    container_name: phoneinfoga
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      webdriverRemote: 'http://selenium-hub:4444/wd/hub'

  selenium-hub:
    image: selenium/hub:3.141.59-palladium
    container_name: selenium-hub
    ports:
      - "4444:4444"

  firefox:
    image: selenium/node-firefox:3.141.59-palladium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - GRID_DEBUG=true