site_name: PhoneInfoga
repo_name: PhoneInfoga
repo_url: 'https://github.com/sundowndev/PhoneInfoga'
site_description: 'Advanced information gathering & OSINT tool for phone numbers.'
site_author: 'Sundowndev'
copyright: 'PhoneInfoga was developed by sundowndev and is licensed under GPL-3.0.'
nav:
  - Introduction: index.md
  - Installation: install.md
  - Basic usage: usage.md
  - Formatting phone numbers: formatting.md
  - Dealing with Google captcha: googlesearch.md
  - Resources: resources.md
  - Contribute: contribute.md
theme:
  name: material
  palette:
    primary: 'blue grey'
    accent: 'brown'