apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-phoneinfoga-app
  name: demo-phoneinfoga-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo-phoneinfoga-app
  template:
    metadata:
      labels:
        app: demo-phoneinfoga-app
    spec:
      containers:
        - image: sundowndev/phoneinfoga@sha256:44dd2b438361a6418f4534df6faea683dd125bf818363465f2921ef31cbeee5f
          args:
            - serve
          name: demo-phoneinfoga-app
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
