apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-phoneinfoga-app
  name: demo-phoneinfoga-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-phoneinfoga-app
  template:
    metadata:
      labels:
        app: demo-phoneinfoga-app
    spec:
      containers:
        - image: sundowndev/phoneinfoga@sha256:d98d28d88540327165f2d25ce1b7d7f253e835b2229e810e59298dd055ef4fe2
          args:
            - serve
          name: demo-phoneinfoga-app
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
