name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        id: publish
        uses: elgohr/Publish-Docker-Github-Action@2.22
        with:
          name: sundowndev/phoneinfoga
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,v2,stable"

      - name: Install yaml processor
        run: |
          wget https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 -O ./yq
          chmod +x ./yq
          
      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Commit new image digest
        run: |
          ./yq w ./.deploy/deployment.yaml 'spec.template.spec.containers[0].image' ${{ steps.publish.outputs.digest }} -i
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./.deploy && git commit -m "deploy: updating docker tag [skip ci]"
          git push origin master
